// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"tiktok.service/biz/dal"
	mv "tiktok.service/biz/middleware"
)

func main() {
	//初始化dal、中间件
	dal.Init()
	mv.InitJwt()

	h := server.Default()

	register(h)
	h.Spin()
}
