// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "tiktok.service/biz/handler"
	middleware "tiktok.service/biz/middleware"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	//注册
	r.POST("/register", handler.Register)

	//登陆
	r.POST("/login", middleware.JwtMiddleware.LoginHandler)
	auth := r.Group("/auth", middleware.JwtMiddleware.MiddlewareFunc())
	auth.GET("/ping", handler.Ping)
}
